### ISSUE TITLE
Not working on MacOS 14.3.1

### ISSUE THREAD

**Issue by thenoseman** [floj/totpgen#1]
Just compiled it and tried to add my first token. This is what happens:
```sh
❯ ./totpgen set test "1234"!
could not insert new secret into keyring: No directory provided for file keyring
zsh: exit 1     ./totpgen set test "1234"!
```
It would be good if it "just works" with the default MacOs keychain but also lets you specify another keychain file if you want to keep the token separate.

Thanks!

**Comment by floj** [comment]
Issue seems to be that cgo is required to interact with the MacOS keychanin. As the `./build.sh` sets `CGO_ENABLED=0`, the library used as an abstraction over the keychanins of multiple OSes falls back to use a file-based store.
